name: Task
description: Create a task
title: "[Task]: "
labels: ["task"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Please decribe the task
  - type: textarea
    id: what-todo
    attributes:
      label: What needs to be done?
      description: Task description
      placeholder: Write it down!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: branch
    attributes:
      label: Branch name
      description: Changes should be executed on what branch?
      placeholder: main
    validations:
      required: true
 
